// portfolio-next/src/app/page.tsx
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  // Calculate years that have passed since January of 2020
  const calculateYearsOfExperience = () => {
    const now = new Date();
    const start = new Date(2020, 0, 1);
    const diff = now.getTime() - start.getTime();
    return Math.round(diff / (1000 * 60 * 60 * 24 * 365));
  };

  const yearsOfExperience = calculateYearsOfExperience();

  return (
    <div className="min-h-screen bg-white text-gray-900">
      {/* Hero Section */}
      <section className="container mx-auto px-4 py-16 md:py-24">
        <div className="max-w-4xl mx-auto text-center">
          <div className="mb-8">
            <Image
              src="/mountains-cut.jpg"
              alt="Mountain landscape"
              width={800}
              height={300}
              className="w-full h-64 object-cover rounded-lg"
              priority
            />
          </div>
          
          <h1 className="text-4xl md:text-6xl font-light mb-8 leading-tight">
            Hello, I&apos;m Juan, a{" "}
            <span className="font-medium">Full Stack Engineer</span>{" "}
            with {yearsOfExperience} years of experience
          </h1>
          
          <p className="text-lg md:text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            I like to make minimalist websites, focusing on functionality and performance,
            keeping the essence of each application
          </p>
          
          <div className="flex justify-center mb-16">
            <Link 
              href="https://www.linkedin.com/in/juan-vera/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:text-blue-700 transition-colors"
            >
              <svg className="w-8 h-8" fill="currentColor" viewBox="0 0 24 24">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
            </Link>
          </div>
        </div>
      </section>

      {/* Projects Section */}
      <section className="container mx-auto px-4 py-16">
        <div className="max-w-6xl mx-auto">
          <div className="grid md:grid-cols-2 gap-12">
            
            {/* Finances Project */}
            <div className="group">
              <h2 className="text-2xl font-medium mb-4">Finances</h2>
              <Link 
                href="https://juanvera.dev/finances"
                target="_blank"
                rel="noopener noreferrer"
                className="block"
              >
                <div className="mb-4">
                  <Image
                    src="/finances.png"
                    alt="Finances app screenshot"
                    width={600}
                    height={400}
                    className="w-full h-64 object-cover rounded-lg group-hover:opacity-90 transition-opacity"
                  />
                </div>
                <p className="text-gray-600">
                  Manage your accounts, set reminders for debts and services
                </p>
              </Link>
            </div>

            {/* Encarga Project */}
            <div className="group">
              <h2 className="text-2xl font-medium mb-4">Encarga</h2>
              <Link 
                href="https://encargarpedido.web.app/"
                target="_blank"
                rel="noopener noreferrer"
                className="block"
              >
                <div className="mb-4">
                  <Image
                    src="/encarga.webp"
                    alt="Encarga app screenshot"
                    width={600}
                    height={400}
                    className="w-full h-64 object-cover rounded-lg group-hover:opacity-90 transition-opacity"
                  />
                </div>
                <div className="space-y-1 text-gray-600">
                  <p>Create your shop</p>
                  <p>Let your clients order</p>
                  <p>Receive automatic messages</p>
                </div>
              </Link>
            </div>
            
          </div>
        </div>
      </section>
    </div>
  );
}

// app.vue
<template>
  <div class="container">

    <Head>
      <Title>Juan Vera - Full Stack Web Developer</Title>
    </Head>
    <div class="header"></div>
    <main class="main">
      <!-- Main Info -->
      <section id="main-info-section" class="section">
        <!-- Profile -->
        <div class="square">
          <img class="profile-img" src="assets/mountains-cut.jpeg" />
        </div>
        <!-- About -->
        <div class="square info-square square-about square-with-padding">
          <h1 class="title">Hello, I'm Juan, a Full Stack Engineer with {{ yearsOfExperience }} years of experience</h1>
          <p class="about-text">I like to make minimalist websites, focusing on functionality and performance, keeping the
            essence of each application</p>
          <div class="contact">
            <a href="https://www.linkedin.com/in/juan-vera/" target="_blank">
              <img src="assets/icons/linkedin.svg" class="link-linkedin" />
            </a>
          </div>
        </div>
      </section>
      <!-- Projects -->
      <section id="projects-section" class="section">
        <!-- Finances -->
        <div class="square project-square square-finances project-vertical square-with-padding">
          <div class="title-and-link">
            <h2 class="project-title">Finances</h2>
            <a href="https://juanvera.dev/finances" target="_blank">
              <img src="assets/icons/arrow-up-right-from-square-solid.svg" class="project-link" />
            </a>
          </div>
          <p class="project-subtitle">Manage your accounts, set reminders for debts and services</p>
          <img src="assets/projects/finances.png" class="project-image" />
        </div>
        <!-- Encarga -->
        <div class="square project-square square-encarga project-vertical square-with-padding">
          <div class="title-and-link">
            <h2 class="project-title">Encarga</h2>
            <a href="https://encargarpedido.web.app/" target="_blank">
              <img src="assets/icons/arrow-up-right-from-square-solid.svg" class="project-link" />
            </a>
          </div>
          <div class="info-and-photo-horizontal">
            <ul class="thin-list">
              <li>Create your shop</li>
              <li>Let your clients order</li>
              <li>Receive automatic messages</li>
            </ul>
            <img src="assets/projects/encarga.webp" class="project-image" />
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<script setup>
   const yearsOfExperience = computed(() => {
      // Calculate years that have passed since January of 2020
      const now = new Date();
      const start = new Date(2020, 0, 1);
      const diff = now.getTime() - start.getTime();
      return Math.round(diff / (1000 * 60 * 60 * 24 * 365));
   });
</script>

<style>
.container {
  max-width: 1200px;
  margin: auto;
  padding-left: 0.75rem;
  padding-right: 0.75rem;
}

.header {
  height: 32px;
}

.main {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section {
  display: flex;
  gap: 16px;
  justify-content: center;
}

.square {
  border-radius: 24px;
}

.square-with-padding {
  padding: 20px;
}

.project-vertical {
  display: flex;
  flex-direction: column;
}

.info-and-photo-horizontal {
  display: flex;
  column-gap: 12px;
}

.project-info {
  display: flex;
  flex-direction: column;
  max-width: 128px;
}

.thin-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  row-gap: 16px;
}

.project-subtitle {
  margin-top: 0px;
}

.project-image {
  margin: auto;
  max-width: 100%;
  max-height: 400px;
}

.profile-img {
  border-radius: 24px;
  max-height: 400px;
  object-fit: cover;
}

.title-and-link {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.project-link {
  width: 20px;
  /** white color */
  filter: invert(100%) sepia(0%) saturate(0%) hue-rotate(158deg) brightness(101%) contrast(101%);
}

.project-link:hover {
  filter: none;
}

@media (min-width: 768px) {
  .title {
    font-size: 40px;
    line-height: 47px;
  }

  .square {
    max-width: 400px;
  }

  .profile-img {
    width: calc(40vw - 40px);
    max-width: 400px;
  }
}

@media (min-width: 992px) {
  .container {
    padding-left: 3rem !important;
    padding-right: 3rem !important;
  }
}

@media (max-width: 767px) {
  .section {
    flex-direction: column !important;
    gap: 0;
  }

  .square {
    margin: 10px;
  }

  .profile-img {
    width: 100%;
  }
}

.square-about {
  background: #e8f3ff;
}

.square-finances {
  background-color: rgb(31, 110, 31);
  color: white;
}

.square-encarga {
  background: linear-gradient(to bottom, #eb3349, #f45c43);
  color: white;
}

.about-text {
  font-style: normal;
  font-weight: 400;
  font-size: 16px;
  line-height: 151.34%;
}

.link-linkedin:hover {
  filter: invert(23%) sepia(80%) saturate(2382%) hue-rotate(197deg) brightness(95%) contrast(92%);
}
</style>
